name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Clang
        run: sudo apt-get install -y clang-format-19

      - name: Run clang-format
        run: |
          clang-format-19 -i --style=file **/*.cpp **/*.h
          
      - name: Check for formatting changes
        run: |
          git diff --exit-code || (echo "Code is not formatted correctly" && exit 1)
